wandb_version: 1

config_file:
  desc: null
  value: ../../experiments/sac/halfcheetah_reinforce1.yaml
eval_interval:
  desc: null
  value: 5000
num_eval_trajectories:
  desc: null
  value: 10
num_render_trajectories:
  desc: null
  value: 10
seed:
  desc: null
  value: 1
no_gpu:
  desc: null
  value: false
which_gpu:
  desc: null
  value: 0
log_interval:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720280048
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.8.19
      5: 0.17.0
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
