wandb_version: 1

env_name:
  desc: null
  value: Humanoid-v4
exp_name:
  desc: null
  value: humanoid
n_iter:
  desc: null
  value: 1000
use_reward_to_go:
  desc: null
  value: true
use_baseline:
  desc: null
  value: true
baseline_learning_rate:
  desc: null
  value: 0.005
baseline_gradient_steps:
  desc: null
  value: 50
gae_lambda:
  desc: null
  value: 0.97
normalize_advantages:
  desc: null
  value: true
batch_size:
  desc: null
  value: 50000
eval_batch_size:
  desc: null
  value: 400
discount:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.001
n_layers:
  desc: null
  value: 3
layer_size:
  desc: null
  value: 256
ep_len:
  desc: null
  value: 1000
seed:
  desc: null
  value: 1
no_gpu:
  desc: null
  value: false
which_gpu:
  desc: null
  value: 0
video_log_freq:
  desc: null
  value: 5
scalar_log_freq:
  desc: null
  value: 1
action_noise_std:
  desc: null
  value: 0
logdir:
  desc: null
  value: /home/seongsu/PycharmProjects/CS285/hw2/cs285/scripts/../../data/q2_pg_humanoid_Humanoid-v4_05-07-2024_15-24-15
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720160656
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.8.19
      5: 0.17.0
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
